import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import localFont from "next/font/local";
import Providers from "./providers";
import "./globals.css";

const montserrat = Montserrat({
  weight: ["300", "400", "500"],
  variable: "--font-montserrat",
  subsets: ["latin", "cyrillic"],
});

const revival = localFont({
  src: [
    {
      weight: "700",
      path: "../fonts/Revival 565 Bold BT.ttf",
    },
  ],
  variable: "--font-revival",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="uk">
      <body
        className={`${montserrat.variable} ${revival.variable} relative z-[1] antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
